backend:
  name: github
  repo: teamtext2/text2   # đã sửa đúng repo của em
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: posts
    label: "Bài viết"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
