backend:
  name: github
  repo: text2team/text2   # ví dụ: text2team/text2-website
  branch: main

media_folder: "static/uploads"     # nơi lưu ảnh trong repo
public_folder: "/uploads"          # URL công khai

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "posts"                # thư mục chứa file .md
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
